FROM python:3.7
RUN pip install opencv-python-headless pyclipper fastapi numpy Pillow uvicorn onnxruntime shapely python-multipart
COPY ./app /app
CMD [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "15400" ]